language: python
python:
  - "2.7"
#  - "3.4" # Comment out to speed up build
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install .
# command to run tests
script:
  - pytest
deploy:
  provider: pypi
  user: "markusschanta"
  password:
    secure: qijNBjRToxGJUykBfNu05hzUgX9X8N0g5fjTYACs9hA4g/pI27tYi33Zn+W3CQOUb15xH/BbJ6uy++XY220lAy/bNNE9ZMfgltRmKY7AL4gcCPeB2n9J7hwTx8u2irvL32l47o7VwJnP27JnbQouihqKS8dEizCTe1GGUtMhX3QLP3T6xh0DtOjIWi7Xk030TGjse8PjT7lFXou//AUw3CVqVK84B4xcWkyYcTat4a7iV28gcHp8/PRdrbKsZCb+oupUee/KYZ/7xXmKfIKaaOmpCNbinLRkLuBYtDOpV6ry8yAF2H5LJ5shahRu/IuXSd5YFOtGDhny2bMet9FsDwPbnu1UZbcUC5/nAa8ddspbj3gUeP1v1hL9cpJ7p4058f4N75VbITx/0EBKQ3a0nqrpAQgzNJbqcyR7Dui2LjALM87Wz4cfQwzSnRM74hfroRQh5wR7I8q/yRAPzdYipmgIdToelkCQV9DVc14z2qfb6SCs2TYE1Dn5m9BIN1AJ6m3I7GFQ2sAJID3+tDAg5vKk3aDPiQnL4E7v52A90ylM5glclKQ2w3lSPoYzfYnZvZa6WaUShPtt5imN/g3KbvlaCQU9sSGf79Fk9e2oft9U8azE7KR1j1oDUX4GtsURzsJPKLC5meWEqhvSDu0NqQESj9LI8kCeErlErF70MgA=
